feat: on chain router
galacticcouncil/hydration-node pull request #699
Opened 2023-11-08 11:37 UTC by dmoka

## Description

Extending the route-executor pallet with on-chain route storing functionality.

Usages:
- Using on-chain route in DCA
- Using on-chain route in Route-Executor if no route is specified
- ExchangeAsset should use on-chain route.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Checklist:

- [x] I have updated the documentation if necessary.
- [x] I have added tests to cover my changes, regression test if fixing an issue.
- [ ] This is a breaking change.

2023-11-15 00:05 UTC, mrq1911 requested changes

2023-11-15 00:05 UTC, mrq1911 commented on pallets/route-executor/src/lib.rs
> +		let default_route = vec![Trade {
nice, so you are keeping our current fallback alive

2023-11-15 00:05 UTC, mrq1911 commented on pallets/route-executor/src/lib.rs
> +		let default_route = vec![Trade {
that probably means that you should actually test against it if the omnipool route is not already set in router and not just take any route

2023-11-17 11:52 UTC, dmoka commented on pallets/omnipool/src/router_execution.rs
> +		let asset_state = Self::load_asset_state(asset_a).map_err(ExecutorError::Error)?;
That might be indeed good to check.

On the other hand, we discussed that LRNA won't be supported in onchain routing.

![image](https://github.com/galacticcouncil/HydraDX-node/assets/9437108/99a380ec-fbae-4aa9-a45a-5b1484b4ea5c)

2023-11-24 11:39 UTC, mrq1911 commented on pallets/omnipool/src/router_execution.rs
> +		let asset_state = Self::load_asset_state(asset_a).map_err(ExecutorError::Error)?;
yeah, buying LRNA will always fail currently, therefore we cannot really store that route as we cannot validate it

2023-11-27 16:04 UTC, mrq1911 approved these changes

2023-11-27 16:04 UTC, merged